version: '3.6'

services:
  pdb:
    image: postgres
    restart: always
    container_name: postgres-db
    environment:
      POSTGRES_PASSWORD: postgrespassword
    ports:
      - 6543:5432
    volumes:
      - ./db-data:/var/lib/postgresql/data
  adminer:
    image: adminer
    depends_on:
      - pdb
    restart: always
    ports:
      - 8888:8080
  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - pdb
    ports:
      - 7070:80
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    restart: unless-stopped
  app:
    image: 'restservice:1.0.0'
    build:
      context: .
    container_name: restservice
    depends_on:
      - pdb
    ports:
      - 8081:8081
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/postgres
      - SPRING_DATASOURCE_URERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgrespassword
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
networks:
  my-network: